version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4001:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --force_polling --livereload --host 0.0.0.0 --verbose
